title : Writing!
tagline: No tagline! Just writing!
author :
  name : Liu Minsheng
  email : notcome@me.com
  github : liums
  twitter : notcome
  weibo : notcome

navigation :
  - finder.html
  - life.html
  - about.md

